version: '3'
services:
  postgres:
    image: postgres:10.5-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - /Users/scott/.fib/data:/var/lib/postgresql/data
  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on: 
      - "postgres"
      - "redis"
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on: 
      - "redis"
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3050:80"
    depends_on: 
      - "client"
      - "api"
    
      