apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  app.config: |
    {
        "host": "redis",
        "port": "6379"
    }
  package.json: |
    { 
        "dependencies": {
            "redis": "*"
        }
    }

  