apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend
  labels:
    tier: frontend
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: external-port
      port: 8081
      targetPort: 80
      nodePort: 30080